import re

def extract_strings_from_file(filename):
    with open(filename, 'r', encoding='utf-8') as file:
        content = file.read()

    # Extract strings inside double quotes (ignoring escaped quotes)
    matches = re.findall(r'(?<!\\)"(.*?)(?<!\\)"', content)

    print("Extracted Strings:")
    for i, string in enumerate(matches, 1):
        print(f"{string}")

# Example usage
if __name__ == "__main__":
    path = input("Enter the path to the Python file: ").strip()
    extract_strings_from_file(path)
    
def generate_pot(strings, filename="messages.pot"):
    with open(filename, 'w', encoding='utf-8') as f:
        f.write('msgid ""\n')
        f.write('msgstr ""\n')
        f.write('"Content-Type: text/plain; charset=UTF-8\\n"\n\n')
        
        for i, s in enumerate(strings, start=1):
            f.write(f'#: string_{i}\n')
            f.write(f'msgid "{s}"\n')
            f.write('msgstr ""\n\n')

strings = [
    "SecureVote | Decentralized Voting",
    "wide",
    "expanded",
    "English",
    "Hindi",
    "Tamil",
    "Punjabi",
    "Marathi",
    "language",
    "Language",
    "Test translation for welcome",
    "id",
    "name",
    "party",
    "color",
    "avatar",
    "Creates a floating particle animation background",
    "Interactive 3D blockchain visualization",
    "Advanced face scanning effect",
    "Initialize all session state variables",
    "Generate a simulated fingerprint hash with visual feedback",
    "Fingerprint verified!",
    "Enhanced face capture with visual feedback",
    "Failed to access camera",
    "Hold still... {3-int(elapsed)}",
    "One-time admin setup process",
    "👑 Admin Setup",
    "This is a one-time setup to create the system administrator",
    "Admin Name",
    "Your full name",
    "Admin ID",
    "Unique admin identifier",
    "Set Admin PIN (6 digits)",
    "Register Admin",
    "PIN must be exactly 6 digits",
    "Please look at the camera for facial registration",
    "Admin account created successfully!",
    "Please complete all fields",
    "Two-factor authentication for admin access",
    "🔒 Admin Authentication",
    "Admin privileges require face and PIN verification",
    "Step 1: Face Verification",
    "Start Face Scan",
    "Admin face verified!",
    "No matching admin found",
    "Step 2: PIN Verification",
    "Enter Admin PIN",
    "Verify PIN",
    "Admin authenticated successfully!",
    "Incorrect PIN",
    "🚀 Decentralized Voting System",
    "Get Started",
    "Key Features",
    "Facial Recognition",
    "Advanced AI verifies voter identity",
    "Fingerprint Auth",
    "Biometric security layer",
    "Blockchain Backed",
    "Immutable transaction ledger",
    "Real-time Results",
    "Live updating analytics",
    "Transparent",
    "Publicly verifiable records",
    "End-to-End Secure",
    "Military-grade encryption",
    "👤 Voter Registration",
    "Full Name",
    "Enter your full name",
    "Voter ID",
    "Unique voter identifier",
    "Begin Biometric Enrollment",
    "This Voter ID is already registered",
    "Securing your data on the blockchain...",
    "Generating cryptographic hash...",
    "Creating transaction...",
    "Mining block...",
    "Registration complete!",
    "You are now registered to vote!",
    "Voter Verification",
    "Enter your Voter ID",
    "Start Verification",
    "Voter ID not found",
    "Please look at the camera for verification",
    "VERIFIED",
    "NOT MATCHING",
    "Identity verified!",
    "Verification failed",
    "🗳️ Cast Your Vote",
    "Voter not found in registry",
    "You have already voted in this election",
    "Select Your Candidate",
    "Vote for {candidate['name']}",
    "Recording vote for {candidate['name']}...",
    "Vote for {candidate['name']} recorded!",
    "📊 Live Election Results",
    "Participation Metrics",
    "Total Registered",
    "Votes Cast",
    "Leading Candidate",
    "Vote Distribution",
    "Candidate",
    "Votes",
    "Party",
    "Color",
    "Percentage",
    "Vote Share",
    "Voting Activity Over Time",
    "Votes per Hour",
    "Time",
    "Protected admin dashboard - only accessible by admin",
    "👑 Administrator Dashboard",
    "ADMIN PRIVILEGES ACTIVATED",
    "📈 Statistics",
    "⛓ Blockchain",
    "⚙ System",
    "Voter Analytics",
    "Date",
    "Daily Registrations",
    "Votes by Hour",
    "Blockchain Explorer",
    "Latest Blocks",
    "Block",
    "Transactions",
    "Timestamp",
    "Hash",
    "Block Hash",
    "System Controls",
    "Critical Operations - Use with caution",
    "🗑️ Reset All Data",
    "System reset complete!",
    "🔐 Generate Security Report",
    "Analyzing system...",
    "Security audit complete",
    "blockchain_integrity",
    "verified",
    "voter_data_encryption",
    "enabled",
    "biometric_protection",
    "active",
    "threat_level",
    "low",
    "Data Management",
    "💾 Export Blockchain Data",
    "🏠 Home",
    "👤 Register",
    "🗳️ Vote",
    "📊 Results",
    "👑 Admin",
    "Navigation",
    "Logout Admin",
    "System Status",
    "Voters",
    "Votes"
]

generate_pot(strings)
